version: "3.8"

services:
  mt5:
    build:
      dockerfile: Dockerfile
    container_name: mt5-master
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./config:/config
      - ./app:/app
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    restart: unless-stopped
    labels:
      # Enable Traefik reverse proxy
      traefik.enable: true
      traefik.docker.network: traefik-public

      ########################################
      # VNC Interface (Port 3000)
      ########################################
      traefik.http.routers.vnc-mt5master-http.rule: Host(`${VNC_DOMAIN}`)
      traefik.http.routers.vnc-mt5master-http.entrypoints: http
      traefik.http.routers.vnc-mt5master-http.middlewares: https-redirect

      traefik.http.routers.vnc-mt5master-https.rule: Host(`${VNC_DOMAIN}`)
      traefik.http.routers.vnc-mt5master-https.entrypoints: https
      traefik.http.routers.vnc-mt5master-https.tls: true
      traefik.http.routers.vnc-mt5master-https.tls.certresolver: le
      traefik.http.routers.vnc-mt5master-https.service: vnc-mt5master-service

      traefik.http.services.vnc-mt5master-service.loadbalancer.server.port: 3000

      ########################################
      # API Interface (Port 5001)
      ########################################
      traefik.http.routers.api-mt5master-http.rule: Host(`${API_DOMAIN}`)
      traefik.http.routers.api-mt5master-http.entrypoints: http
      traefik.http.routers.api-mt5master-http.middlewares: https-redirect

      traefik.http.routers.api-mt5master-https.rule: Host(`${API_DOMAIN}`)
      traefik.http.routers.api-mt5master-https.entrypoints: https
      traefik.http.routers.api-mt5master-https.tls: true
      traefik.http.routers.api-mt5master-https.tls.certresolver: le
      traefik.http.routers.api-mt5master-https.service: api-mt5master-service

      traefik.http.services.api-mt5master-service.loadbalancer.server.port: 5001

networks:
  default:
    driver: bridge
  traefik-public:
    external: true
