services:
  mt5:
    build:
      dockerfile: Dockerfile
    container_name: mt5-ers
    volumes:
      - ./config:/config
    networks:
      - default
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    driver: bridge
